In [35]:
import numpy as np
a=np.array([1,2,3],dtype='int64');
print(a+5);
a.dtype



[6 7 8]


dtype('int64')

In [48]:
b=np.array([[2,5,6],[6,6,7],[10,11,12],[111,222,333]])
print(b)
b.ndim
b.shape
b.dtype



[[  2   5   6]
 [  6   6   7]
 [ 10  11  12]
 [111 222 333]]


dtype('int64')

In [49]:
b.nbytes

96

In [50]:
b[1,1]

6

In [51]:
b[:,2]

array([  6,   7,  12, 333])

In [60]:
b[2,1:]

array([11, 12])

In [62]:
b[2,2]=1000
print(b)

[[   2    5    6]
 [   6    6    7]
 [  10   11 1000]
 [ 111  222  333]]


In [68]:
np.zeros((2,3,4,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [71]:
np.ones((4,4),dtype='int16')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [79]:
np.full((2,9),99,dtype='float32')

array([[99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99.]], dtype=float32)

In [81]:
np.full(b.shape,4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [83]:
np.full_like(b,4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [91]:
np.random.random_sample(b.shape)

array([[0.41751101, 0.61921855, 0.58523698],
       [0.91129369, 0.69833582, 0.41451903],
       [0.85189943, 0.08844354, 0.37825305],
       [0.75008289, 0.82903948, 0.09225127]])

In [102]:
np.random.rand(5,3)

array([[0.97161959, 0.95294163, 0.53551936],
       [0.47813089, 0.10519969, 0.14041876],
       [0.48273108, 0.28847519, 0.94335398],
       [0.03968122, 0.36743661, 0.97883097],
       [0.79998976, 0.72835933, 0.95497202]])

In [103]:
np.random.randint(7,size=(3,3))

array([[2, 5, 5],
       [0, 1, 1],
       [3, 3, 5]])

In [105]:
np.random.randint(-100,5,size=(4,4))

array([[-30,   4, -64, -27],
       [-35, -69, -94, -46],
       [-23, -42, -53, -24],
       [-11, -33, -70, -14]])

In [114]:
#indentity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [120]:
c=np.repeat(b,3,axis=0)
print(c)

[[   2    5    6]
 [   2    5    6]
 [   2    5    6]
 [   6    6    7]
 [   6    6    7]
 [   6    6    7]
 [  10   11 1000]
 [  10   11 1000]
 [  10   11 1000]
 [ 111  222  333]
 [ 111  222  333]
 [ 111  222  333]]


In [153]:
test=np.ones((5,5),dtype='int')
print(test)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [165]:

test[1:4,1:4]=0
test[2,2]=9
print(test)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [163]:
test[1:4,1:4]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])